<Project>
  <PropertyGroup>
    <BuildInParallel>false</BuildInParallel>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RestorePackagesWithLockFile Condition="'$(MSBuildProjectName)' != 'GolfSG'">true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(CI)' == 'true' and '$(MSBuildProjectName)' != 'GolfSG'">true</RestoreLockedMode>
    <!-- Release versioning. Use scripts\Set-AppVersion.ps1 to update these. -->
    <VersionPrefix>0.3.0</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
    <ApplicationBuildNumber>4</ApplicationBuildNumber>
    <Version>$(VersionPrefix)</Version>
    <Version Condition="'$(VersionSuffix)' != ''">$(VersionPrefix)-$(VersionSuffix)</Version>
    <AssemblyVersion>$(VersionPrefix).0</AssemblyVersion>
    <FileVersion>$(VersionPrefix).$(ApplicationBuildNumber)</FileVersion>
    <InformationalVersion>$(VersionPrefix)+build.$(ApplicationBuildNumber)</InformationalVersion>
    <InformationalVersion Condition="'$(VersionSuffix)' != ''">$(VersionPrefix)-$(VersionSuffix)+build.$(ApplicationBuildNumber)</InformationalVersion>
  </PropertyGroup>
</Project>
